snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USERNAME') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE') }}"
      database: RAW_DATA
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      schema: PUBLIC
      client_session_keep_alive: False

#     # pre:
#     #   type: snowflake
#     #   account: "{{ env_var('SF_PRE_ACCOUNT') }}"
#     #   user: "{{ env_var('SF_PRE_USERNAME') }}"
#     #   password: "{{ env_var('SF_PRE_PASSWORD') }}"
#     #   role: SYSADMIN
#     #   database: "{{ env_var('SF_PRE_DATABASE') }}"
#     #   warehouse: "{{ env_var('SF_PRE_WAREHOUSE') }}"
#     #   schema: REPORT
#     #   client_session_keep_alive: False
