WITH PRODUCTS AS (
SELECT * FROM {{ ref('stg_products') }}
),
DEPARTMENT AS (
SELECT * FROM {{ ref('stg_department') }}
),
AISLE AS (
SELECT * FROM {{ ref('stg_aisle') }}
),
PRODUCTS_DEPARTMENT AS (
SELECT 
P.PRODUCT_ID,
P.PRODUCT_NAME,
P.AISLE_ID,
D.DEPARTMENT
FROM PRODUCTS P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENT_ID = D.DEPARTMENT_ID)
, 
FINAL AS 
(
SELECT 
P.PRODUCT_ID,
P.PRODUCT_NAME, 
A.AISLE,
P.DEPARTMENT
FROM PRODUCTS_DEPARTMENT P
INNER JOIN AISLE A
ON P.AISLE_ID = A.AISLE_ID
)
SELECT * FROM FINAL