WITH PRODUCTS AS (
SELECT AISLE_ID,DEPARTMENT_ID,PRODUCT_ID,PRODUCT_NAME FROM {{ ref('stg_products') }}
),
DEPARTMENT AS (
SELECT DEPARTMENT, DEPARTMENT_ID FROM {{ ref('stg_department') }}
),
AISLE AS (
SELECT AISLE, AISLE_ID FROM {{ ref('stg_aisle') }}
),
PRODUCTS_DEPARTMENT AS (
SELECT 
P.PRODUCT_ID,
P.PRODUCT_NAME,
P.AISLE_ID,
D.DEPARTMENT
FROM PRODUCTS P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENT_ID = D.DEPARTMENT_ID)
, 
FINAL AS 
(
SELECT 
P.PRODUCT_ID,
P.PRODUCT_NAME, 
A.AISLE,
P.DEPARTMENT
FROM PRODUCTS_DEPARTMENT P
INNER JOIN AISLE A
ON P.AISLE_ID = A.AISLE_ID
)
SELECT 
AISLE,
DEPARTMENT,
PRODUCT_ID,
PRODUCT_NAME
 FROM FINAL