name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./

  SF_ACCOUNT: ${{ vars.DEV.SF_ACCOUNT }}
  SF_DATABASE: ${{  vars.DEV.SF_DATABASE }}
  SF_PASSWORD: ${{  vars.DEV.SF_PASSWORD }} 
  SF_ROLE: ${{  vars.DEV.SF_ROLE }}
  SF_SCHEMA: ${{  vars.DEV.SF_SCHEMA }}
  SF_USERNAME: ${{  vars.DEV.SF_USERNAME }}
  SF_WAREHOUSE: ${{  vars.DEV.SF_WAREHOUSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Check out
        uses: actions/checkout@master
        
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"   
         
      - name: Install dependencies
        run: |
         pip install dbt-snowflake
         dbt deps   
      
      - name: Run dbt models
        run: dbt run  --target dev
        
      - name: Test dbt models
        run: dbt test


