name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./

  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_DATABASE: ${{ secrets.SF_DATABASE }}
  SF_PASSWORD: ${{ secrets.SF_PASSWORD }} 
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
