name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_DATABASE: ${{  secrets.SF_DATABASE }}
  SF_PASSWORD: ${{  secrets.SF_PASSWORD }} 
  SF_ROLE: ${{  secrets.SF_ROLE }}
  SF_SCHEMA: ${{  secrets.SF_SCHEMA }}
  SF_USERNAME: ${{  secrets.SF_USERNAME }}
  SF_WAREHOUSE: ${{  secrets.SF_WAREHOUSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
    
  DeployDev: 
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment:
      name: DEV
    env:
      DBT_PROFILES_DIR: ./
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_DATABASE: ${{  secrets.SF_DATABASE }}
      SF_PASSWORD: ${{  secrets.SF_PASSWORD }} 
      SF_ROLE: ${{  secrets.SF_ROLE }}
      SF_SCHEMA: ${{  secrets.SF_SCHEMA }}
      SF_USERNAME: ${{  secrets.SF_USERNAME }}
      SF_WAREHOUSE: ${{  secrets.SF_WAREHOUSE }}
    steps:
      - name: Check out
        uses: actions/checkout@master
    
      - name: Checkout Repository
        uses: actions/checkout@v2  
        
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"   
          
         
      - name: Install dependencies
        run: |
         pip install dbt-snowflake
         dbt deps   
      
      - name: Run dbt models
        id: run_models 
        run: dbt run --target dev

      - name: Test dbt models
        id: run_tests
        run: dbt test
        continue-on-error: true        

      - name: Snowflake Query Action
        uses: anecdotes-ai/snowflake-query@1.1      
        with:
          snowflake_account: ${{ secrets.SF_ACCOUNT }}
          snowflake_password: ${{  secrets.SF_PASSWORD }} 
          snowflake_username: ${{  secrets.SF_USERNAME }}
          snowflake_warehouse: ${{  secrets.SF_WAREHOUSE }}
          queries: 'DROP SCHEMA RAW_DATA.REPORT'
        if: steps.run_tests.outcome == 'failure' 
  
      - name: SQL INGECTION
        uses: anecdotes-ai/snowflake-query@1.1      
        with:
          snowflake_account: ${{ secrets.SF_ACCOUNT }}
          snowflake_password: ${{  secrets.SF_PASSWORD }} 
          snowflake_username: ${{  secrets.SF_USERNAME }}
          snowflake_warehouse: ${{  secrets.SF_WAREHOUSE }}
          queries: 'DROP SCHEMA RAW_DATA.REPORT'
        if: steps.run_tests.outcome == 'failure' 
       
              
      - name: Lint with sqlfluff
        run: |
          pip install sqlfluff
          git fetch origin main:main
          git diff main --name-only --diff-filter=d | egrep '^models/.*sql$$' | xargs -r sqlfluff lint

        
        # Linting only modified models
        # git fetch origin main:main
        # git diff main --name-only --diff-filter=d | egrep '^models/.*sql$$' | xargs -r sqlfluff lint
                
  # sql-review:
  #   runs-on: ubuntu-latest
  #   needs: DeployDev
  #   environment:
  #     name: DEV
  #   env:
  #     DBT_PROFILES_DIR: ./
  #     SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  #     SF_DATABASE: ${{  secrets.SF_DATABASE }}
  #     SF_PASSWORD: ${{  secrets.SF_PASSWORD }} 
  #     SF_ROLE: ${{  secrets.SF_ROLE }}
  #     SF_SCHEMA: ${{  secrets.SF_SCHEMA }}
  #     SF_USERNAME: ${{  secrets.SF_USERNAME }}
  #     SF_WAREHOUSE: ${{  secrets.SF_WAREHOUSE }}

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2  
      
  #   - uses: actions/setup-python@v1
  #     with:
  #       python-version: "3.7.x"   
        
  #   - name: run sqlmap
  #     run: git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
      
  #   - name: runs on python sqlmap.py -h
  #     run: echo ${{ github.workspace }}


  



