name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_DATABASE: ${{  secrets.SF_DATABASE }}
  SF_PASSWORD: ${{  secrets.SF_PASSWORD }} 
  SF_ROLE: ${{  secrets.SF_ROLE }}
  SF_SCHEMA: ${{  secrets.SF_SCHEMA }}
  SF_USERNAME: ${{  secrets.SF_USERNAME }}
  SF_WAREHOUSE: ${{  secrets.SF_WAREHOUSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

    
  DeployDev: 
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment:
      name: DEV
    env:
      DBT_PROFILES_DIR: ./
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_DATABASE: ${{  secrets.SF_DATABASE }}
      SF_PASSWORD: ${{  secrets.SF_PASSWORD }} 
      SF_ROLE: ${{  secrets.SF_ROLE }}
      SF_SCHEMA: ${{  secrets.SF_SCHEMA }}
      SF_USERNAME: ${{  secrets.SF_USERNAME }}
      SF_WAREHOUSE: ${{  secrets.SF_WAREHOUSE }}
    steps:
      - name: Check out
        uses: actions/checkout@master
        
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"   
         
      - name: Install dependencies
        run: |
         pip install dbt-snowflake
         dbt deps   
      
      - name: Run dbt models
        run: dbt run --target dev
        
      - name: Test dbt models
        run: dbt test


