name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./

  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_DATABASE: ${{ secrets.SF_DATABASE }}
  SF_PASSWORD: ${{ secrets.SF_PASSWORD }} 
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Use variables
        run: |
          echo "SF_ACCOUNT variable : $SF_ACCOUNT"
          echo "SF_DATABASE variable : $SF_DATABASE"
          echo "SF_SCHEMA variable : $SF_SCHEMA"

